# Generated by Django 2.2.1 on 2020-04-05 07:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DiabeticRetinopathy', '0002_auto_20200405_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2020, 4, 5, 7, 29, 5, 892500)),
        ),
    ]
